alertmanager:
  alertmanagerSpec:
    useExistingSecret: true
    configSecret: alertmanager-monitoring-config
    secrets:
      - slack-api-url    # mounts Secret at /etc/alertmanager/secrets


prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

grafana:
  adminPassword: "admin123"
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 50m
      memory: 128Mi





# # alertmanager:
# #   enabled: true
# #   # no custom config yet â€“ use chart defaults

# # prometheus:
# #   prometheusSpec:
# #     serviceMonitorSelector: {}
# #     podMonitorSelector: {}

# # kube-state-metrics:
# #   resources:
# #     requests:
# #       cpu: 50m
# #       memory: 64Mi

# # prometheusOperator:
# #   resources:
# #     requests:
# #       cpu: 50m
# #       memory: 128Mi

# # grafana:
# #   adminPassword: "admin123"
# #   service:
# #     type: LoadBalancer
# #   resources:
# #     requests:
# #       cpu: 50m
# #       memory: 128Mi
