apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitoring
  labels:
    release: monitoring     # must match Helm release name
spec:
  groups:
    - name: test.rules
      rules:
        - alert: TestAlwaysFiring
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Test alert from Prometheus"
            description: "This is a test alert that always fires."












# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: slack-test-alert-rule
#   namespace: monitoring
# spec:
#   groups:
#     - name: slack-test-alerts
#       rules:
#         - alert: SlackTestAlert
#           expr: vector(1)
#           for: 1m
#           labels:
#             severity: warning
#           annotations:
#             summary: "Slack test alert - EKS project"
#             description: "This is a test alert to verify Slack notifications for Liliane's EKS Cloud Ready API project."
